version: '3.7'

services:
  api:
    container_name: ura-vocalizadora
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=ura_vocalizadora
      - DB_USER=ura@dev
      - SECRET_KEY=minha_chave_secreta
    volumes:
      - .:/app
  
  db:
    container_name: data_base_ura
    image: postgres:15
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=ura@dev
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ura_vocalizadora
    volumes:
     - db_ura:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db_ura:
    driver: local
   

